### ISSUE TITLE
起動不可

### ISSUE THREAD

**Issue by NekoFuwa1739** [DaisukeDaisuke/AndroidPHP_old#4]
最後のコマンドを入力するとこのようなエラーが出てしまいます。よろしくお願いいたします。
![Screenshot_20210505-115937_Terminal Emulator](https://user-images.githubusercontent.com/62869023/117092673-eea00c80-ad99-11eb-8940-d6f9fd40da1f.jpg)

**Comment by DaisukeDaisuke** [comment]
issuesありがとうございます。
以下のファイルをテキストエディタにて開き、文末に以下の文章を追加していただけませんでしょうか...?
```
/storage/emulated/0/PocketMine/config/php.ini
```
1. 以下のコマンドを実行します。
```
cd /data/data/0/jackpal.androidterm/app_HOME
mkdir tmp
```
2. `/storage/emulated/0/PocketMine/config/php.ini` をテキストエディタにて開き、文末に以下の文章を追加します。
```

sys_temp_dir = /data/data/0/jackpal.androidterm/app_HOME/tmp
```
参考: https://qiita.com/f_uto/items/76d4302dcd84435ae510

**Comment by NekoFuwa1739** [comment]
解決しました出来ました。ありがとうございました。
